[[constraint]]
  name = "k8s.io/client-go"
  version = "v12.0.0"

[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "v1.3.0"

[[constraint]]
  name = "github.com/olekukonko/tablewriter"
  version = "v0.0.4"

[prune]
  go-tests = true
  unused-packages = true